import { Link } from "react-router";
import { useEffect, useRef } from "react";
import $ from "jquery";
import "bootstrap-icons/font/bootstrap-icons.css";
import PageTitle from "../../components/Common-Sections/PageTitle";
window.$ = $;
window.jQuery = $;
function  ReportsPage () {
 const tableRef = useRef(null);
  useEffect(() => {
    const table = $(tableRef.current).DataTable({
      responsive: true,
      pageLength: 5,
      lengthMenu: [5, 15, 20, 25],
      ordering: true,
      searching: true,
      info: true,
      paging: true,
      pagingType: "simple_numbers",
      language: {
        search: "",
        searchPlaceholder: "Search Operation",
        paginate: {
          previous: "Previous",
          next: "Next",
        },
        info: "Showing _START_ To _END_ Of _TOTAL_ Entries",
      },
      dom: '<"d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3"lf>rt<"d-flex justify-content-between align-items-center mt-4 flex-wrap gap-3"ip>',
    });

    return () => {
      if ($.fn.DataTable.isDataTable(tableRef.current)) {
        table.destroy();
      }
    };
  }, []);

   const taskList = [
        {
            id: 1,
            patientName:"John Doe",
            patientReport:" Blood Test Report",
            GeneratedbyDoctor:"Dr. Smith",
            DoctorImage:"public/01.jpg",
            GeneratedDate:"01/03/2025",
        },
        {
            id: 2,
            patientName:"Jane Smith",
            patientReport:" X-Ray Report",
            GeneratedbyDoctor:"Dr. John",
            DoctorImage:"public/02.jpg",
            GeneratedDate:"02/03/2025",
        },
        {
            id: 3,
            patientName:"Robert Brown",
            patientReport:"MRI Scan",
            GeneratedbyDoctor:"Dr. Emily",
            DoctorImage:"public/03.jpg",
            GeneratedDate:"03/03/2025",
        },
         {
            id: 4,
            patientName:"Lisa White",
            patientReport:"ECG Report",
            GeneratedbyDoctor:"Dr. Doe",
            DoctorImage:"public/04.jpg",
            GeneratedDate:"04/03/2025",
        },
        {
            id: 5,
            patientName:"Michael Green",
            patientReport:"Ultrasound Report",
            GeneratedbyDoctor:"Dr. Adams",
            DoctorImage:"public/05.jpg",
            GeneratedDate:"05/03/2025",
        },
       
    ];
  
    return (
        <>
         <PageTitle title="HC-ERP-Reports"/>
             <div className="px-4 mb-4 min-vh-100 outer-main">
        <h4 className="mb-4 fw-600 text-dark-primary mt-2">Reports</h4> 
        <div className="mb-4">
          <div className="bg-white h-100 shadow-sm  rounded-10 mb-4 p-3"> 
            <div className="table-repsonsive px-2 pt-1">
            <table className="table custom-data-table" id="reportstd" ref={tableRef} style={{ width: "100%" }} >
                <thead>
                    <tr>
                        <th className="text-dark-primary  py-2 px-3"><input type="checkbox"/></th> 
                        <th className="text-dark-primary  py-2 px-3">Patient Name</th>
                        <th className="text-dark-primary  py-2 px-3">Patient Report</th>
                        <th className="text-dark-primary  py-2 px-3">Generated by Doctor</th>
                        <th className="text-dark-primary  py-2 px-3">Generated Date</th>
                        <th className="text-dark-primary  py-2 px-3">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {taskList.map((item,index)=>{
                        return (
                            <tr key={index}>
                                <td><input type="checkbox"/></td> 
                                <td className="text-dark ">{item.patientName}</td>
                                <td className="text-dark "><Link to="#"><i className="bi bi-file-pdf text-danger"></i>{item.patientReport}</Link></td>
                                <td className="d-flex">
                                    <div><img src={item.DoctorImage} alt="" width="25" height="25" className="rounded-circle me-2"/></div>
                                    <div className="ms-2 text-dark ">{item.GeneratedbyDoctor}</div>
                                </td>
                                <td className="text-dark ">{item.GeneratedDate}</td>
                                <td className="text-dark">
                                    <button className="btn btn-success btn-sm me-2"><i className="bi bi-download"></i></button>
                                    <button className="btn btn-danger btn-sm"><i className="bi bi-trash"></i></button>
                                </td>
                            </tr>
                        );
                    })}
                </tbody>
            </table> 
            </div>
          </div>
        </div> 
      </div> 
        </>
    );
}
export default ReportsPage